# Import & Load

In [8]:
import logging
logging.getLogger("kedro.io").setLevel(logging.WARNING)
import numpy as np
np.set_printoptions(suppress=True)
np.random.seed(1)
import random
random.seed(1)
import pandas as pd
pd.set_option("max_colwidth", 100)
pd.set_option("display.precision", 3)
import seaborn as sns
sns.set_style("whitegrid")
import matplotlib.pyplot as plt
plt.style.use("ggplot")
plt.rcParams.update({
    "figure.figsize": (8, 5),
    "figure.dpi": 100,
    "savefig.dpi": 300,
    "figure.constrained_layout.use": True,
    "axes.titlesize": 12,
    "axes.labelsize": 10,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 9,
    "legend.title_fontsize": 10,
    "grid.alpha": 1.0,
})
import matplotlib as mpl
from cycler import cycler
mpl.rcParams['axes.prop_cycle'] = cycler(color=["#000000", "#000000"])
mpl.colormaps.register(
    mpl.colors.ListedColormap(
        ["#000000", "#2f2fff"], name="black_and_blue"),
    force=True,
)
mpl.colormaps.register(
    mpl.colors.ListedColormap(
        ["#000000", "#D55E00"], name="black_and_orange"),
    force=True,
)
mpl.colormaps.register(
    mpl.colors.ListedColormap(
        ["#000000", "#000000"], name="black"),
    force=True,
)
mpl.colormaps.register(
    mpl.colors.ListedColormap(
        ["#000000", "#0072B2", "#D55E00"],
        name='black_and_2color',
    ),
    force=True
)
mpl.colormaps.register(
    mpl.colors.ListedColormap(
        ["#000000", "#D55E00", "#0072B2", "#009E73"],
        name='black_and_3color',
    ),
    force=True
)
mpl.colormaps.register(
    mpl.colors.ListedColormap(
        ["#000000", "#D55E00", "#0072B2", "#009E73", "#CC79A7"],
        name='black_and_4color',
    ),
    force=True
)
mpl.colormaps.register(
    mpl.colors.ListedColormap(
        ["#D55E00", "#0072B2", "#009E73", "#CC79A7"],
        name='r_colors',
    ),
    force=True
)

In [10]:
df_anomaly_source = catalog.load("anomaly_source")
df_anomaly_target = catalog.load("anomaly_target")
df_normal_source = catalog.load("normal_source")
df_normal_target = catalog.load("normal_target")

# Overview

In [25]:
print(f"{"-"*10} df_anomaly_source {"-"*10}")
display(df_anomaly_source.head())
print("\n\n")

print(f"{"-"*10} df_anomaly_target {"-"*10}")
display(df_anomaly_target.head())
print("\n\n")

print(f"{"-"*10} df_normal_source {"-"*10}")
display(df_normal_source.head())
print("\n\n")

print(f"{"-"*10} df_normal_target {"-"*10}")
display(df_normal_target.head())

---------- df_anomaly_source ----------

,segment_id,split_label,anomaly_label,domain_shift_op,domain_shift_env,imp23absu_mic,ism330dhcx_acc,ism330dhcx_gyro
0,20240423_17_20_26_segment_0,Anomaly_Source_Test,belt,spd2400,BckgC,imp23absu_mic_20240423_17_20_26_DataLog_0.parquet,ism330dhcx_acc_20240423_17_20_26_DataLog_0.parquet,ism330dhcx_gyro_20240423_17_20_26_DataLog_0.parquet
1,20240423_18_18_56_segment_0,Anomaly_Source_Test,magnetic,spd2800,BckgF,imp23absu_mic_20240423_18_18_56_DataLog_0.parquet,ism330dhcx_acc_20240423_18_18_56_DataLog_0.parquet,ism330dhcx_gyro_20240423_18_18_56_DataLog_0.parquet
2,20240423_17_10_11_segment_0,Anomaly_Source_Test,belt,spd1700,BckgF,imp23absu_mic_20240423_17_10_11_DataLog_0.parquet,ism330dhcx_acc_20240423_17_10_11_DataLog_0.parquet,ism330dhcx_gyro_20240423_17_10_11_DataLog_0.parquet
3,20240423_18_03_58_segment_0,Anomaly_Source_Test,magnetic,spd1700,BckgA,imp23absu_mic_20240423_18_03_58_DataLog_0.parquet,ism330dhcx_acc_20240423_18_03_58_DataLog_0.parquet,ism330dhcx_gyro_20240423_18_03_58_DataLog_0.parquet
4,20240423_17_57_20_segment_0,Anomaly_Source_Test,magnetic,spd1500,BckgA,imp23absu_mic_20240423_17_57_20_DataLog_0.parquet,ism330dhcx_acc_20240423_17_57_20_DataLog_0.parquet,ism330dhcx_gyro_20240423_17_57_20_DataLog_0.parquet

---------- df_anomaly_target ----------

,segment_id,split_label,anomaly_label,domain_shift_op,domain_shift_env,imp23absu_mic,ism330dhcx_acc,ism330dhcx_gyro
0,20240423_16_48_07_segment_0,Anomaly_Target_Test,belt,spd1000,BckgE,imp23absu_mic_20240423_16_48_07_DataLog_0.parquet,ism330dhcx_acc_20240423_16_48_07_DataLog_0.parquet,ism330dhcx_gyro_20240423_16_48_07_DataLog_0.parquet
1,20240423_17_39_58_segment_0,Anomaly_Target_Test,magnetic,spd1000,BckgE,imp23absu_mic_20240423_17_39_58_DataLog_0.parquet,ism330dhcx_acc_20240423_17_39_58_DataLog_0.parquet,ism330dhcx_gyro_20240423_17_39_58_DataLog_0.parquet
2,20240423_16_49_15_segment_0,Anomaly_Target_Test,belt,spd1000,BckgE,imp23absu_mic_20240423_16_49_15_DataLog_0.parquet,ism330dhcx_acc_20240423_16_49_15_DataLog_0.parquet,ism330dhcx_gyro_20240423_16_49_15_DataLog_0.parquet
3,20240423_17_38_31_segment_0,Anomaly_Target_Test,magnetic,spd1000,BckgB,imp23absu_mic_20240423_17_38_31_DataLog_0.parquet,ism330dhcx_acc_20240423_17_38_31_DataLog_0.parquet,ism330dhcx_gyro_20240423_17_38_31_DataLog_0.parquet
4,20240423_16_55_21_segment_0,Anomaly_Target_Test,belt,spd1200,BckgG,imp23absu_mic_20240423_16_55_21_DataLog_0.parquet,ism330dhcx_acc_20240423_16_55_21_DataLog_0.parquet,ism330dhcx_gyro_20240423_16_55_21_DataLog_0.parquet

---------- df_normal_source ----------

,segment_id,split_label,anomaly_label,domain_shift_op,domain_shift_env,imp23absu_mic,ism330dhcx_acc,ism330dhcx_gyro
0,20240423_14_23_48_segment_0,Normal_Source_Test,normal,spd1800,BckgD,imp23absu_mic_20240423_14_23_48_DataLog_0.parquet,ism330dhcx_acc_20240423_14_23_48_DataLog_0.parquet,ism330dhcx_gyro_20240423_14_23_48_DataLog_0.parquet
1,20240423_14_44_40_segment_0,Normal_Source_Test,normal,spd1900,BckgC,imp23absu_mic_20240423_14_44_40_DataLog_0.parquet,ism330dhcx_acc_20240423_14_44_40_DataLog_0.parquet,ism330dhcx_gyro_20240423_14_44_40_DataLog_0.parquet
2,20240423_14_13_22_segment_0,Normal_Source_Test,normal,spd1800,BckgA,imp23absu_mic_20240423_14_13_22_DataLog_0.parquet,ism330dhcx_acc_20240423_14_13_22_DataLog_0.parquet,ism330dhcx_gyro_20240423_14_13_22_DataLog_0.parquet
3,20240423_13_03_46_segment_0,Normal_Source_Test,normal,spd1500,BckgA,imp23absu_mic_20240423_13_03_46_DataLog_0.parquet,ism330dhcx_acc_20240423_13_03_46_DataLog_0.parquet,ism330dhcx_gyro_20240423_13_03_46_DataLog_0.parquet
4,20240423_13_45_54_segment_0,Normal_Source_Test,normal,spd1700,BckgF,imp23absu_mic_20240423_13_45_54_DataLog_0.parquet,ism330dhcx_acc_20240423_13_45_54_DataLog_0.parquet,ism330dhcx_gyro_20240423_13_45_54_DataLog_0.parquet

---------- df_normal_target ----------

,segment_id,split_label,anomaly_label,domain_shift_op,domain_shift_env,imp23absu_mic,ism330dhcx_acc,ism330dhcx_gyro
0,20240423_12_16_58_segment_0,Normal_Target_Test,normal,spd1400,BckgE,imp23absu_mic_20240423_12_16_58_DataLog_0.parquet,ism330dhcx_acc_20240423_12_16_58_DataLog_0.parquet,ism330dhcx_gyro_20240423_12_16_58_DataLog_0.parquet
1,20240423_11_26_43_segment_0,Normal_Target_Test,normal,spd1200,BckgG,imp23absu_mic_20240423_11_26_43_DataLog_0.parquet,ism330dhcx_acc_20240423_11_26_43_DataLog_0.parquet,ism330dhcx_gyro_20240423_11_26_43_DataLog_0.parquet
2,20240423_10_48_48_segment_0,Normal_Target_Test,normal,spd1100,BckgE,imp23absu_mic_20240423_10_48_48_DataLog_0.parquet,ism330dhcx_acc_20240423_10_48_48_DataLog_0.parquet,ism330dhcx_gyro_20240423_10_48_48_DataLog_0.parquet
3,20240423_11_53_19_segment_0,Normal_Target_Test,normal,spd1300,BckgE,imp23absu_mic_20240423_11_53_19_DataLog_0.parquet,ism330dhcx_acc_20240423_11_53_19_DataLog_0.parquet,ism330dhcx_gyro_20240423_11_53_19_DataLog_0.parquet
4,20240423_12_17_27_segment_0,Normal_Target_Test,normal,spd1400,BckgE,imp23absu_mic_20240423_12_17_27_DataLog_0.parquet,ism330dhcx_acc_20240423_12_17_27_DataLog_0.parquet,ism330dhcx_gyro_20240423_12_17_27_DataLog_0.parquet

In [36]:
print(f"{"-"*10} df_anomaly_source {"-"*10}")
print(df_anomaly_source.anomaly_label.value_counts())
print("\n")
print(f"{"-"*10} df_anomaly_target {"-"*10}")
print(df_anomaly_target.anomaly_label.value_counts())
print("\n")
print(f"{"-"*10} df_normal_source {"-"*10}")
print(df_normal_source.anomaly_label.value_counts())
print("\n")
print(f"{"-"*10} df_normal_target {"-"*10}")
print(df_normal_target.anomaly_label.value_counts())

---------- df_anomaly_source ----------
anomaly_label
belt        39
magnetic    39
Name: count, dtype: int64


---------- df_anomaly_target ----------
anomaly_label
belt        42
magnetic    36
Name: count, dtype: int64


---------- df_normal_source ----------
anomaly_label
normal    78
Name: count, dtype: int64


---------- df_normal_target ----------
anomaly_label
normal    78
Name: count, dtype: int64

In [37]:
print(f"{"-"*10} df_anomaly_source {"-"*10}")
print(df_anomaly_source.domain_shift_op.value_counts())
print("\n")
print(f"{"-"*10} df_anomaly_target {"-"*10}")
print(df_anomaly_target.domain_shift_op.value_counts())
print("\n")
print(f"{"-"*10} df_normal_source {"-"*10}")
print(df_normal_source.domain_shift_op.value_counts())
print("\n")
print(f"{"-"*10} df_normal_target {"-"*10}")
print(df_normal_target.domain_shift_op.value_counts())

---------- df_anomaly_source ----------
domain_shift_op
spd1900    10
spd2400     9
spd2800     9
spd1700     9
spd1500     9
spd3000     8
spd1600     8
spd2000     8
spd1800     8
Name: count, dtype: int64


---------- df_anomaly_target ----------
domain_shift_op
spd1000    16
spd1300    16
spd1100    16
spd1200    15
spd1400    15
Name: count, dtype: int64


---------- df_normal_source ----------
domain_shift_op
spd1800    9
spd1700    9
spd3000    9
spd2400    9
spd2800    9
spd2000    9
spd1900    8
spd1500    8
spd1600    8
Name: count, dtype: int64


---------- df_normal_target ----------
domain_shift_op
spd1400    16
spd1300    16
spd1000    16
spd1200    15
spd1100    15
Name: count, dtype: int64

In [38]:
print(f"{"-"*10} df_anomaly_source {"-"*10}")
print(df_anomaly_source.domain_shift_env.value_counts())
print("\n")
print(f"{"-"*10} df_anomaly_target {"-"*10}")
print(df_anomaly_target.domain_shift_env.value_counts())
print("\n")
print(f"{"-"*10} df_normal_source {"-"*10}")
print(df_normal_source.domain_shift_env.value_counts())
print("\n")
print(f"{"-"*10} df_normal_target {"-"*10}")
print(df_normal_target.domain_shift_env.value_counts())

---------- df_anomaly_source ----------
domain_shift_env
BckgA    23
BckgC    19
BckgF    18
BckgD    18
Name: count, dtype: int64


---------- df_anomaly_target ----------
domain_shift_env
BckgG    27
BckgB    26
BckgE    25
Name: count, dtype: int64


---------- df_normal_source ----------
domain_shift_env
BckgA    24
BckgD    18
BckgC    18
BckgF    18
Name: count, dtype: int64


---------- df_normal_target ----------
domain_shift_env
BckgE    27
BckgB    26
BckgG    25
Name: count, dtype: int64

In [49]:
print(f"{"-"*20} domain_shift_op & anomaly_label Categories Count {"-"*20}")
print("\n")
print(f"{"-"*10} df_anomaly_source {"-"*10}")
print(df_anomaly_source[["anomaly_label", "domain_shift_op"]].value_counts())
print("\n")
print(f"{"-"*10} df_anomaly_target {"-"*10}")
print(df_anomaly_target[["anomaly_label", "domain_shift_op"]].value_counts())
print("\n")
print(f"{"-"*10} df_normal_source {"-"*10}")
print(df_normal_source[["anomaly_label", "domain_shift_op"]].value_counts())
print("\n")
print(f"{"-"*10} df_normal_source {"-"*10}")
print(df_normal_target[["anomaly_label", "domain_shift_op"]].value_counts())
print("\n\n\n")

print(f"{"-"*20} domain_shift_env & anomaly_label Categories Count {"-"*20}")
print("\n")
print(f"{"-"*10} df_anomaly_source {"-"*10}")
print(df_anomaly_source[["anomaly_label", "domain_shift_env"]].value_counts())
print("\n")
print(f"{"-"*10} df_anomaly_target {"-"*10}")
print(df_anomaly_target[["anomaly_label", "domain_shift_env"]].value_counts())
print("\n")
print(f"{"-"*10} df_normal_source {"-"*10}")
print(df_normal_source[["anomaly_label", "domain_shift_env"]].value_counts())
print("\n")
print(f"{"-"*10} df_normal_source {"-"*10}")
print(df_normal_target[["anomaly_label", "domain_shift_env"]].value_counts())
print("\n\n\n")

print(f"{"-"*20} domain_shift_op & domain_shift_env Categories Count {"-"*20}")
print("\n")
print(f"{"-"*10} df_anomaly_source {"-"*10}")
print(df_anomaly_source[["domain_shift_op", "domain_shift_env"]].value_counts())
print("\n")
print(f"{"-"*10} df_anomaly_target {"-"*10}")
print(df_anomaly_target[["domain_shift_op", "domain_shift_env"]].value_counts())
print("\n")
print(f"{"-"*10} df_normal_source {"-"*10}")
print(df_normal_source[["domain_shift_op", "domain_shift_env"]].value_counts())
print("\n")
print(f"{"-"*10} df_normal_source {"-"*10}")
print(df_normal_target[["domain_shift_op", "domain_shift_env"]].value_counts())
print("\n\n\n")

-------------------- domain_shift_op & anomaly_label Categories Count --------------------


---------- df_anomaly_source ----------
anomaly_label  domain_shift_op
magnetic       spd2800            5
belt           spd1700            5
magnetic       spd2400            5
belt           spd1900            5
               spd1500            5
magnetic       spd1900            5
belt           spd2400            4
magnetic       spd1700            4
               spd1500            4
belt           spd3000            4
magnetic       spd1600            4
belt           spd2000            4
magnetic       spd3000            4
belt           spd1800            4
               spd1600            4
magnetic       spd2000            4
               spd1800            4
belt           spd2800            4
Name: count, dtype: int64


---------- df_anomaly_target ----------
anomaly_label  domain_shift_op
belt           spd1000            9
               spd1100            9
               spd1300            9
               spd1200            8
magnetic       spd1400            8
               spd1000            7
               spd1300            7
               spd1200            7
               spd1100            7
belt           spd1400            7
Name: count, dtype: int64


---------- df_normal_source ----------
anomaly_label  domain_shift_op
normal         spd1800            9
               spd1700            9
               spd3000            9
               spd2400            9
               spd2800            9
               spd2000            9
               spd1900            8
               spd1500            8
               spd1600            8
Name: count, dtype: int64


---------- df_normal_source ----------
anomaly_label  domain_shift_op
normal         spd1400            16
               spd1300            16
               spd1000            16
               spd1200            15
               spd1100            15
Name: count, dtype: int64




-------------------- domain_shift_env & anomaly_label Categories Count --------------------


---------- df_anomaly_source ----------
anomaly_label  domain_shift_env
belt           BckgA               12
magnetic       BckgA               11
               BckgC               10
belt           BckgC                9
magnetic       BckgF                9
belt           BckgF                9
magnetic       BckgD                9
belt           BckgD                9
Name: count, dtype: int64


---------- df_anomaly_target ----------
anomaly_label  domain_shift_env
belt           BckgE               14
               BckgG               14
               BckgB               14
magnetic       BckgG               13
               BckgB               12
               BckgE               11
Name: count, dtype: int64


---------- df_normal_source ----------
anomaly_label  domain_shift_env
normal         BckgA               24
               BckgD               18
               BckgC               18
               BckgF               18
Name: count, dtype: int64


---------- df_normal_source ----------
anomaly_label  domain_shift_env
normal         BckgE               27
               BckgB               26
               BckgG               25
Name: count, dtype: int64




-------------------- domain_shift_op & domain_shift_env Categories Count --------------------


---------- df_anomaly_source ----------
domain_shift_op  domain_shift_env
spd1700          BckgA               3
spd1500          BckgA               3
spd2800          BckgA               3
spd2400          BckgA               3
spd1900          BckgA               3
                 BckgC               3
spd2400          BckgC               2
spd2800          BckgF               2
spd1700          BckgF               2
spd3000          BckgA               2
spd1600          BckgA               2
spd1500          BckgD               2
spd2000          BckgA               2
spd1600          BckgF               2
spd3000          BckgF               2
spd1500          BckgF               2
spd2400          BckgD               2
spd1800          BckgA               2
spd2000          BckgD               2
spd1700          BckgD               2
spd1500          BckgC               2
spd1800          BckgF               2
                 BckgC               2
spd2000          BckgF               2
spd1900          BckgF               2
spd2800          BckgC               2
spd1900          BckgD               2
spd3000          BckgC               2
spd2000          BckgC               2
spd2800          BckgD               2
spd1800          BckgD               2
spd3000          BckgD               2
spd2400          BckgF               2
spd1600          BckgC               2
                 BckgD               2
spd1700          BckgC               2
Name: count, dtype: int64


---------- df_anomaly_target ----------
domain_shift_op  domain_shift_env
spd1000          BckgB               6
spd1200          BckgG               6
spd1300          BckgG               6
spd1400          BckgB               6
spd1100          BckgG               6
spd1000          BckgE               5
                 BckgG               5
spd1200          BckgE               5
spd1100          BckgE               5
                 BckgB               5
spd1400          BckgE               5
spd1300          BckgB               5
                 BckgE               5
spd1400          BckgG               4
spd1200          BckgB               4
Name: count, dtype: int64


---------- df_normal_source ----------
domain_shift_op  domain_shift_env
spd1800          BckgA               3
spd2800          BckgA               3
spd1700          BckgA               3
spd3000          BckgA               3
spd2400          BckgA               3
spd2000          BckgA               3
spd1800          BckgD               2
spd1900          BckgC               2
spd1500          BckgA               2
spd1700          BckgF               2
spd3000          BckgD               2
spd1800          BckgC               2
spd1900          BckgF               2
spd1700          BckgC               2
spd2400          BckgD               2
spd3000          BckgF               2
spd1900          BckgA               2
spd2000          BckgC               2
spd1700          BckgD               2
spd1600          BckgF               2
spd2400          BckgF               2
spd1500          BckgD               2
spd1800          BckgF               2
spd1500          BckgF               2
spd1600          BckgA               2
spd2000          BckgF               2
spd2400          BckgC               2
spd2000          BckgD               2
spd1600          BckgD               2
spd3000          BckgC               2
spd1500          BckgC               2
spd1900          BckgD               2
spd2800          BckgD               2
                 BckgC               2
spd1600          BckgC               2
spd2800          BckgF               2
Name: count, dtype: int64


---------- df_normal_source ----------
domain_shift_op  domain_shift_env
spd1400          BckgE               6
spd1000          BckgE               6
spd1300          BckgB               6
spd1200          BckgG               5
spd1100          BckgE               5
spd1300          BckgE               5
spd1000          BckgB               5
spd1100          BckgB               5
spd1400          BckgG               5
                 BckgB               5
spd1000          BckgG               5
spd1300          BckgG               5
spd1200          BckgE               5
                 BckgB               5
spd1100          BckgG               5
Name: count, dtype: int64

In [ ]:
# Falta truncar as séries temporais para ficarem todas com o mesmo tamanho
# falta separar por treino, val, test